server.port=8080
spring.application.name=resume-analyzer
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
nvidia.api.key.parse=${NVIDIA_API_KEY_PARSE}
nvidia.api.key.analyze=${NVIDIA_API_KEY_ANALYZE}
minimax.api.key=${MINIMAX_API_KEY}
nvidia.api.key=${NVIDIA_API_KEY}
